# Site settings
title: Harsh Sarda
email:
  id: harshsarda987@gmail.com
  show_on_home: true
  show_in_contact: true
description: >
  Software Developer
baseurl: "/" 
url: "https://sardaharsh.github.io"
author:
  street_address: Sarda Niwas, Vivekanand Nagar
  city: Parli
  state: Maharashtra
  zip_code: 431515
  country: India
  phone: +91 9403324332

icon: fa-diamond
remote_theme: andrewbanchich/dimension-jekyll-theme

github:
  url: https://github.com/sardaharsh
  show_on_home: true
  show_in_contact: true
gitlab:
  url: ""
  show_on_home: false
  show_in_contact: false
linkedin:
  url: https://www.linkedin.com/in/harsh-sarda-a01851239/
  show_on_home: true
  show_in_contact: true
leetcode:
  url: "https://leetcode.com/u/sardaharsh/"
  show_on_home: true
  show_in_contact: true
instagram:
  url: https://www.instagram.com/sarda.harsh/
  show_on_home: true
  show_in_contact: true

# Build settings
markdown: kramdown

sass:
  style: compressed
